[workspace]
members = ["contracts/ibc-router/*", "packages/ibc-0.16/*"]

[profile.release.package.mars]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
