[package]
name = "mars"
version = "0.1.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.2"
cosmwasm-std = "0.14.1"
cosmwasm-bignumber = "2.1.0"
terra-cosmwasm = "2.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "2.2.1"
