on: push

name: Basic


jobs:
  build-mars-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build artifacts
        run: $GITHUB_WORKSPACE/scripts/build_artifacts.sh
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mars-artifacts
          path: |
            artifacts

  build-astroport-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Astroport repo
        uses: actions/checkout@v2
        with:
          repository: astroport-fi/astroport-core
          path: astroport-core
      - name: build artifacts
        run: |
          ls -alh
          cd astroport-core
          ls -alh
          ./scripts/build_artifacts.sh
  test:
    runs-on: ubuntu-latest
    needs: build-mars-artifacts
    strategy:
      matrix:
        tests: [
            { name: borrow_exact_liquidity, block-time: 250 },
            { name: dynamic_interest_rate_thresholds, block-time: 250 }
        ]
    env:
      CW_PLUS_ARTIFACTS_PATH: /home/runner/work/cw-plus-artifacts
    steps:
      - uses: actions/checkout@v2
      - name: download cw-plus artifacts
        run: |
          mkdir $CW_PLUS_ARTIFACTS_PATH
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.9.1/cw1_whitelist.wasm -O $CW_PLUS_ARTIFACTS_PATH/cw1_whitelist.wasm
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.9.1/cw20_base.wasm -O $CW_PLUS_ARTIFACTS_PATH/cw20_base.wasm
      - name: download mars artifacts
        uses: actions/download-artifact@v2
        with:
          name: mars-artifacts
          path: artifacts
      - name: npm install
        run: |
          cd $GITHUB_WORKSPACE/scripts
          npm install
          npm install -g typescript
          npm install -g ts-node
      - name: LocalTerra
        run: |
          cd
          git clone --depth 1 https://github.com/terra-money/LocalTerra.git
          sed -E -i '/timeout_(propose|prevote|precommit|commit)/s/[0-9]+m?s/${{ matrix.tests.block-time }}ms/' LocalTerra/config/config.toml
          docker-compose -f $HOME/LocalTerra/docker-compose.yml up -d
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/scripts
          ls -alh ../artifacts
          node --loader ts-node/esm tests/${{ matrix.tests.name }}.ts
      - name: stop LocalTerra
        run: docker-compose -f $HOME/LocalTerra/docker-compose.yml down
