on: push

name: Basic

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build artifacts
        run: $GITHUB_WORKSPACE/scripts/build_artifacts.sh
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            artifacts
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test: [borrow_exact_liquidity]
    steps:
      - uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: npm install
        run: |
          cd $GITHUB_WORKSPACE/scripts
          npm install
      - name: LocalTerra
        run: |
          cd
          git clone --depth 1 https://github.com/terra-money/LocalTerra.git
          sed -E -i '/timeout_(propose|prevote|precommit|commit)/s/[0-9]+m?s/200ms/' LocalTerra/config/config.toml
          docker-compose -f $HOME/LocalTerra/docker-compose.yml up -d
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/scripts
          node --loader ts-node/esm tests/${{ matrix.test }}.ts
      - name: stop LocalTerra
        run: docker-compose -f $HOME/LocalTerra/docker-compose.yml down
