on: push

name: Basic

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: LocalTerra
        run: |
          cd $HOME
          git clone --depth 1 https://github.com/terra-money/LocalTerra.git
          sed -E -i '/timeout_(propose|prevote|precommit|commit)/s/[0-9]+m?s/200ms/' LocalTerra/config/config.toml
      - name: checkout repo
        uses: actions/checkout@v2
      - name: npm install
        run: |
          cd $GITHUB_WORKSPACE/scripts
          ls
          pwd
          npm install
  borrow_exact_liquidity:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: start LocalTerra
        run: |
          cd $HOME
          ls
          pwd
          docker-compose -f $HOME/LocalTerra/docker-compose.yml up -d
      - name: run test
        run: |
          cd scripts
          node --loader ts-node/esm tests/borrow_exact_liquidity.ts
      - name: stop LocalTerra
        run: docker-compose -f $HOME/LocalTerra/docker-compose.yml down
